name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.10.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build source
        run: pnpm build
      - name: Fetch data
        run: pnpm run fetch
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
      - name: Render SVG
        run: go run .
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Update files
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              colors.json
              colors.svg
            commit-msg: |
              auto: update at ${{ env.date }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
